name: .NET with Coverage

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Coverlet Collector
      run: dotnet tool install --global coverlet.collector
    - name: Build
      run: dotnet build --no-restore
    - name: Test with Coverage
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/
    - name: Check Coverage
      run: |
        coverlet ./TestResults/coverage.cobertura.xml --threshold 90